pipeline:
  build:
    image: plugins/docker
    repo: kyleterry/sufr
    secrets: [ docker_username, docker_password ]
    custom_dns: [ 1.1.1.1, 8.8.8.8 ]
    auto_tag: true
    when:
      branch: master
      event: [ push, pull_request, tag ]
