-- Code generated by build_sql.awk; DO NOT EDIT.
select
  users.id as id,
  users.email as email,
  users.password_hash as password_hash,
  coalesce(
    nullif(users.api_token, ''), ''
  ) as api_token,
  users.embed_content as embed_content,
  users.created_at as created_at,
  users.updated_at as updated_at
from users
where users.email = ?;
