-- Code generated by build_sql.awk; DO NOT EDIT.
select
  users.id as id,
  users.email as email,
  users.embed_content as embed_content,
  users.created_at as created_at,
  users.updated_at as updated_at
from users
where users.id = ?;
