-- Code generated by build_sql.awk; DO NOT EDIT.
select
  json_extract(cats.value, '$.label') as label,
  json_object('items',
    json_array(
      json_set(jt.value, '$.name', t.name)
    )
  ) as tags
from users
left join json_each(users.pinned_categories) cats
left join json_each(json_extract(cats.value, '$.tags')) jt
left join tags t on t.id = json_extract(jt.value, '$.id')
where users.id = ? and users.pinned_categories != '[]'
