-- Code generated by build_sql.awk; DO NOT EDIT.
update users
  set pinned_categories = (
  select
    json_group_array(
      json_object('label', label, 'tags', tags))
  from (
    select
      json_extract(cats.value, '$.label') as label,
      json_group_array(
        json_object('id',
          json_extract(items.value, '$.id'))) as tags
    from json_each(json(?)) cats
    join json_each(cats.value, '$.tags.items') items
    group by json_extract(cats.value, '$.label')))
where id = ?
