-- Code generated by build_sql.awk; DO NOT EDIT.
insert into user_urls
  (id, user_id, url_id, title, favorite, created_at, updated_at)
values
  (:id, :user.id, :url.id, :title, :favorite, :created_at, :updated_at)
