BEGIN {
    currentfile = ""
    dialect = ""
}

/^-- sufr:dialect/ {
    if (dialect != "") {
        print "WARN: dialect already set to: " dialect
        print "WARN: use '-- sufr:dialect' only once"
    }

    dialect = $3
}

{
    if (dialect == "") {
        print "ERROR: expected '-- sufr:dialect <name>' on the first line."
        print "ERROR: supported dialects are: sqlite"
        exit 1
    }
}

/^-- sufr:map_query/ {
    if (NF > 3) {
        print "ERROR: malformed annotation: " $0
        print "ERROR: '-- sufr:map_query <name>': name must not contain a space"
        exit 1
    }

    currentfile = "sql/" dialect "/" $3 ".generated.sql"

    print "-- Code generated by build_sql.awk; DO NOT EDIT." > currentfile

    next
}

NF {
    if (currentfile != "") {
        print > currentfile
    }
}
